#!/bin/bash

FOLDER_PATH="$1"
QUERY="$2"
FILE="$3"

echo "FOLDER_PATH: $FOLDER_PATH"
echo "QUERY: $QUERY"
echo "FILE: $FILE"

cd $FOLDER_PATH
find . -name "*.java" \
  | xargs grep --color -l "$QUERY" \
  | sed -e 's/^\.\//"/g' -e 's/$/"/g' \
  | jq -s 'map({path:., borderColor:"#00ff00", fillColor:"#00ff00"})' \
  > $FILE



